"""init

Revision ID: 774fd9a8fa12
Revises: 6c36a0f32c4c
Create Date: 2023-01-05 20:39:36.994147

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774fd9a8fa12'
down_revision = '6c36a0f32c4c'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def data_upgrades():
    """optional data upgrade migrations go here"""
    pass

def data_downgrades():
    """optional data downgrade migrations go here"""
    pass
